/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'case-studies': CaseStudy;
    services: Service;
    'team-members': TeamMember;
    clients: Client;
    'approved-facts': ApprovedFact;
    redirects: Redirect;
    'ai-usage': AiUsage;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'approved-facts': ApprovedFactsSelect<false> | ApprovedFactsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'ai-usage': AiUsageSelect<false> | AiUsageSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
    theme: Theme;
    'search-profile': SearchProfile;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    'search-profile': SearchProfileSelect<false> | SearchProfileSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  decorative?: boolean | null;
  caption?: string | null;
  /**
   * Provide the page title, nearby copy and purpose to help draft an accurate description.
   */
  context?: string | null;
  altSource?: ('manual' | 'ai-draft' | 'decorative' | 'needs-review') | null;
  demo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  summary: string;
  order?: number | null;
  /**
   * Demo records are excluded from production search indexing.
   */
  demo?: boolean | null;
  publishedAt?: string | null;
  heroMedia?: {
    image?: (number | null) | Media;
    altOverride?: string | null;
    decorative?: boolean | null;
  };
  composition?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  services?: (number | Service)[] | null;
  caseStudies?: (number | CaseStudy)[] | null;
  evidence?: (number | ApprovedFact)[] | null;
  aiAssisted?: boolean | null;
  claimsReviewed?: boolean | null;
  seo?: {
    /**
     * Defaults to the page title and company name.
     */
    title?: string | null;
    description?: string | null;
    canonical?: string | null;
    noindex?: boolean | null;
    socialTitle?: string | null;
    socialDescription?: string | null;
    socialImage?: (number | null) | Media;
    topic?: string | null;
    intent?: string | null;
    questions?:
      | {
          question: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  summary: string;
  order?: number | null;
  /**
   * Demo records are excluded from production search indexing.
   */
  demo?: boolean | null;
  publishedAt?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroMedia?: {
    image?: (number | null) | Media;
    altOverride?: string | null;
    decorative?: boolean | null;
  };
  video?: {
    vimeoId?: string | null;
    title?: string | null;
    description?: string | null;
    poster?: (number | null) | Media;
    uploadDate?: string | null;
    transcript?: string | null;
  };
  capabilities?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  showInNavigation?: boolean | null;
  caseStudies?: (number | CaseStudy)[] | null;
  related?: (number | Service)[] | null;
  evidence?: (number | ApprovedFact)[] | null;
  aiAssisted?: boolean | null;
  claimsReviewed?: boolean | null;
  seo?: {
    /**
     * Defaults to the page title and company name.
     */
    title?: string | null;
    description?: string | null;
    canonical?: string | null;
    noindex?: boolean | null;
    socialTitle?: string | null;
    socialDescription?: string | null;
    socialImage?: (number | null) | Media;
    topic?: string | null;
    intent?: string | null;
    questions?:
      | {
          question: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  summary: string;
  order?: number | null;
  /**
   * Demo records are excluded from production search indexing.
   */
  demo?: boolean | null;
  publishedAt?: string | null;
  client?: (number | null) | Client;
  year?: number | null;
  narrative?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featured?: boolean | null;
  heroMedia?: {
    image?: (number | null) | Media;
    altOverride?: string | null;
    decorative?: boolean | null;
  };
  thumbnail?: {
    image?: (number | null) | Media;
    altOverride?: string | null;
    decorative?: boolean | null;
  };
  video?: {
    vimeoId?: string | null;
    title?: string | null;
    description?: string | null;
    poster?: (number | null) | Media;
    uploadDate?: string | null;
    transcript?: string | null;
  };
  gallery?:
    | {
        asset?: {
          image?: (number | null) | Media;
          altOverride?: string | null;
          decorative?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Include only outcomes supported by evidence.
   */
  results?: string | null;
  services?: (number | Service)[] | null;
  credits?:
    | {
        person?: (number | null) | TeamMember;
        contribution?: string | null;
        id?: string | null;
      }[]
    | null;
  related?: (number | CaseStudy)[] | null;
  evidence?: (number | ApprovedFact)[] | null;
  aiAssisted?: boolean | null;
  claimsReviewed?: boolean | null;
  seo?: {
    /**
     * Defaults to the page title and company name.
     */
    title?: string | null;
    description?: string | null;
    canonical?: string | null;
    noindex?: boolean | null;
    socialTitle?: string | null;
    socialDescription?: string | null;
    socialImage?: (number | null) | Media;
    topic?: string | null;
    intent?: string | null;
    questions?:
      | {
          question: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  website?: string | null;
  logo?: (number | null) | Media;
  demo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  portrait?: {
    image?: (number | null) | Media;
    altOverride?: string | null;
    decorative?: boolean | null;
  };
  alternatePortrait?: {
    image?: (number | null) | Media;
    altOverride?: string | null;
    decorative?: boolean | null;
  };
  bio?: string | null;
  longBio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  active?: boolean | null;
  demo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approved-facts".
 */
export interface ApprovedFact {
  id: number;
  statement: string;
  category: 'company' | 'capability' | 'client' | 'project' | 'result' | 'award' | 'testimonial' | 'location' | 'other';
  sourceNote: string;
  sourceURL?: string | null;
  verification: 'pending' | 'verified' | 'rejected';
  verifiedAt?: string | null;
  reviewAt?: string | null;
  client?: (number | null) | Client;
  project?: (number | null) | CaseStudy;
  service?: (number | null) | Service;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-usage".
 */
export interface AiUsage {
  id: number;
  key: string;
  count: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'approved-facts';
        value: number | ApprovedFact;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'ai-usage';
        value: number | AiUsage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  decorative?: T;
  caption?: T;
  context?: T;
  altSource?: T;
  demo?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  order?: T;
  demo?: T;
  publishedAt?: T;
  heroMedia?:
    | T
    | {
        image?: T;
        altOverride?: T;
        decorative?: T;
      };
  composition?: T;
  services?: T;
  caseStudies?: T;
  evidence?: T;
  aiAssisted?: T;
  claimsReviewed?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noindex?: T;
        socialTitle?: T;
        socialDescription?: T;
        socialImage?: T;
        topic?: T;
        intent?: T;
        questions?:
          | T
          | {
              question?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  order?: T;
  demo?: T;
  publishedAt?: T;
  client?: T;
  year?: T;
  narrative?: T;
  featured?: T;
  heroMedia?:
    | T
    | {
        image?: T;
        altOverride?: T;
        decorative?: T;
      };
  thumbnail?:
    | T
    | {
        image?: T;
        altOverride?: T;
        decorative?: T;
      };
  video?:
    | T
    | {
        vimeoId?: T;
        title?: T;
        description?: T;
        poster?: T;
        uploadDate?: T;
        transcript?: T;
      };
  gallery?:
    | T
    | {
        asset?:
          | T
          | {
              image?: T;
              altOverride?: T;
              decorative?: T;
            };
        id?: T;
      };
  results?: T;
  services?: T;
  credits?:
    | T
    | {
        person?: T;
        contribution?: T;
        id?: T;
      };
  related?: T;
  evidence?: T;
  aiAssisted?: T;
  claimsReviewed?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noindex?: T;
        socialTitle?: T;
        socialDescription?: T;
        socialImage?: T;
        topic?: T;
        intent?: T;
        questions?:
          | T
          | {
              question?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  order?: T;
  demo?: T;
  publishedAt?: T;
  description?: T;
  heroMedia?:
    | T
    | {
        image?: T;
        altOverride?: T;
        decorative?: T;
      };
  video?:
    | T
    | {
        vimeoId?: T;
        title?: T;
        description?: T;
        poster?: T;
        uploadDate?: T;
        transcript?: T;
      };
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  showInNavigation?: T;
  caseStudies?: T;
  related?: T;
  evidence?: T;
  aiAssisted?: T;
  claimsReviewed?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noindex?: T;
        socialTitle?: T;
        socialDescription?: T;
        socialImage?: T;
        topic?: T;
        intent?: T;
        questions?:
          | T
          | {
              question?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  portrait?:
    | T
    | {
        image?: T;
        altOverride?: T;
        decorative?: T;
      };
  alternatePortrait?:
    | T
    | {
        image?: T;
        altOverride?: T;
        decorative?: T;
      };
  bio?: T;
  longBio?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  order?: T;
  active?: T;
  demo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  website?: T;
  logo?: T;
  demo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approved-facts_select".
 */
export interface ApprovedFactsSelect<T extends boolean = true> {
  statement?: T;
  category?: T;
  sourceNote?: T;
  sourceURL?: T;
  verification?: T;
  verifiedAt?: T;
  reviewAt?: T;
  client?: T;
  project?: T;
  service?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-usage_select".
 */
export interface AiUsageSelect<T extends boolean = true> {
  key?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  primary?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  secondary?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footer?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  description?: string | null;
  email?: string | null;
  phone?: string | null;
  footerText?: string | null;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultShareImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  canvas: string;
  surface: string;
  text: string;
  muted: string;
  accent: string;
  highlight: string;
  border: string;
  inverse: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-profile".
 */
export interface SearchProfile {
  id: number;
  companyDescription?: string | null;
  proposition?: string | null;
  audiences?: string | null;
  sectors?: string | null;
  markets?: string | null;
  differentiators?: string | null;
  customerQuestions?: string | null;
  objectives?: string | null;
  topics?: string | null;
  searchIntents?: string | null;
  tone?: string | null;
  approvedTerminology?: string | null;
  prohibitedClaims?: string | null;
  researchNotes?: string | null;
  services?: (number | Service)[] | null;
  approvedFacts?: (number | ApprovedFact)[] | null;
  referenceURLs?:
    | {
        url: string;
        approved?: boolean | null;
        id?: string | null;
      }[]
    | null;
  allowSearchCrawlers?: boolean | null;
  allowTrainingCrawlers?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primary?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  secondary?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  description?: T;
  email?: T;
  phone?: T;
  footerText?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  defaultShareImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  canvas?: T;
  surface?: T;
  text?: T;
  muted?: T;
  accent?: T;
  highlight?: T;
  border?: T;
  inverse?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-profile_select".
 */
export interface SearchProfileSelect<T extends boolean = true> {
  companyDescription?: T;
  proposition?: T;
  audiences?: T;
  sectors?: T;
  markets?: T;
  differentiators?: T;
  customerQuestions?: T;
  objectives?: T;
  topics?: T;
  searchIntents?: T;
  tone?: T;
  approvedTerminology?: T;
  prohibitedClaims?: T;
  researchNotes?: T;
  services?: T;
  approvedFacts?: T;
  referenceURLs?:
    | T
    | {
        url?: T;
        approved?: T;
        id?: T;
      };
  allowSearchCrawlers?: T;
  allowTrainingCrawlers?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'case-studies';
          value: number | CaseStudy;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}